[workspace]
members = [
  "crates/md-docrs-core",
  "crates/md-docrs-fetch-http",
  "crates/md-docrs-cli",
  "crates/md-docrs-server",
  "crates/md-docrs-worker",
  "crates/md-docrs-rust-wasm",
  "crates/md-docrs-wasm-compare",
]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
anyhow = "1"
async-trait = "0.1"
axum = { version = "0.8", default-features = false }
bytes = "1"
clap = { version = "4", features = ["derive"] }
foyer = { version = "0.22", features = ["serde"] }
lru = "0.17"
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls"] }
rustdoc-types = "0.57"
serde = { version = "1", features = ["derive", "rc"] }
serde_json = "1"
thiserror = "2"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "sync"] }
tower-http = { version = "0.6", features = ["trace"] }
tower-service = "0.3.3"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
worker = "0.8.1"
worker-macros = "0.8.1"
zstd = "0.13"

[profile.release.package.md-docrs-rust-wasm]
opt-level = "z"
codegen-units = 1
strip = true

[profile.wasm-release]
inherits = "release"
opt-level = "z"
lto = "fat"
codegen-units = 1
strip = true
panic = "abort"
