[package]
name = "md-docrs-wasm-compare"
version.workspace = true
edition.workspace = true
publish = false

[[bin]]
name = "wasm-compare"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
blake3 = "1"
reqwest = { workspace = true, features = ["blocking", "gzip"] }
wasmtime = "44"
wasmer = { version = "7", optional = true }

[features]
default = []
